apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelatman-playground
  template:
    metadata:
      labels:
        app: yelatman-playground
  spec:
      containers:
      - name: yelatman-playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
