apiVersion: v1
kind: Service
metadata:
  name: yelatman-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: yelatman-playground
  ports:
    - protocol: TCP
      port: 80         # The port the service exposes
      targetPort: 8888