apiVersion: v1
kind: Service
metadata:
  name: yelatman-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: yelatman-playground
  ports:
    - protocol: TCP
      port: 8888         # The port the service exposes
      targetPort: 8888
